on:
  workflow_dispatch:
  
jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan ZAP website
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Date and Filename
        id: date
        run: |
          echo "DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
          echo "FILENAME=zap_scan_$DATE.html" >> $GITHUB_ENV

      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.10.0
        with:
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          target: 'https://alkiratest.portal.alkira.com/'
          report: true
          report_name: ${{ env.FILENAME }}

      - name: Save Report
        if: always()
        run: |
          mkdir -p reports
          mv ${{ env.FILENAME }} reports/
          echo "Report saved as reports/${{ env.FILENAME }}"

      - name: Error Handling
        if: failure()
        run: |
          echo "zap scan failed"
          exit 1
