on:
  workflow_dispatch:
  
jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan ZAP website
    steps:
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.12.0
        with:
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          target: 'https://alkiratest.portal.alkira.com/'
          
      - uses: actions/upload-artifact@v4
        with:
          name: zap_scan%D%M%Y
  
      - name: error handling
        if: ${{ failure() }}
        run: |
          echo: "zap scan failed"
          exit 1
