name: OWASP ZAP Integration with GitHub Actions

on:
  schedule:
    # Runs every month at 9am UTC time.
    - cron: '30 10 * * *'

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the web application
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main

      - name: ZAP Scan
        id: zap_scan_step
        uses: zaproxy/action-baseline@v0.10.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          target: 'https://google.com/'

      # Error handling
      - name: Check for errors
        if: ${{ failure() }}
        run: |
          echo "ZAP scan failed!"
          exit 1
